const Router = require('express')
const router = new Router()
const dealController = require('../controlers/dealController')

router.post('/create', dealController.create)
router.post('/get', dealController.get)
router.post('/getById', dealController.getById)
router.post('/update', dealController.updateDeal)
router.post('/delete', dealController.deleteDeal)
router.get('/distinct', dealController.distinct)
router.get('/agregation', dealController.agregation)
router.get('/between', dealController.between)
router.get('/exists', dealController.exists)
router.get('/having', dealController.having)
router.get('/in', dealController.in)
router.get('/intersect', dealController.intersect)
router.get('/orderBy', dealController.orderBy)
router.get('/trDirty', dealController.transactionsDirty)

module.exports = router