const Router = require('express')
const router = new Router()
const clientRouter = require('./clientRouter')
const dealRouter = require('./dealRouter')
const workerRouter = require('./workerRouter')
const clientContactRouter = require('./clientContactRouter')
const productRouter = require('./productRouter')
const dealDocumentRouter = require('./dealDocumentRouter')
const userRouter = require('./userRouter')
const applicationRouter = require('./applicationRouter')
const dealStatusRouter = require('./dealStatusRouter')
const timeTypeRouter = require('./timeTypeRouter')

router.use('/deal', dealRouter)
router.use('/client', clientRouter)
router.use('/clientContact', clientContactRouter)
router.use('/worker', workerRouter)
router.use('/product', productRouter)
router.use('/dealDocument', dealDocumentRouter)
router.use('/user', userRouter)
router.use('/application', applicationRouter)
router.use('/dealStatus', dealStatusRouter)
router.use('/timeType', timeTypeRouter)

module.exports = router